### ISSUE TITLE
超类调用问题？

### ISSUE THREAD

**Issue by Z-fly** [cdhigh/Vb6Tkinter#14]
![image](https://user-images.githubusercontent.com/10470892/99928094-a5777580-2d82-11eb-8a30-3ef34f68d34b.png)
请问Pycharm提示的缺少超类调用是什么意思？

**Comment by cdhigh** [comment]
Pycharm会那么笨？
Frame.__init__(self, master)是老的调用基类方法，
super.__init__(master)是新的方法，
Python到目前为止还是支持两种方法的，考虑tkinter designer的创建时间，那个时候只有第一种写法能兼容2.x和3.x，现在pycharm竟然不认了。
不过以后可以考虑改成super调用方法。

**Comment by Z-fly** [comment]
> Pycharm会那么笨？
> Frame.**init**(self, master)是老的调用基类方法，
> super.**init**(master)是新的方法，
> Python到目前为止还是支持两种方法的，考虑tkinter designer的创建时间，那个时候只有第一种写法能兼容2.x和3.x，现在pycharm竟然不认了。
> 不过以后可以考虑改成super调用方法。

那么可以这样，选择兼容时采用 Frame.**init**(self, master)，只要Python3的就用super调用

**Comment by cdhigh** [comment]
python2官方已经停止支持，我的电脑上都已经卸载了python2，所以现在还无法确认python2.7是否支持super调用，不过也可以考虑不再支持python2了。

**Comment by hlizard** [comment]
我倒希望一直保持已有的python2支持， 正规新项目选python 3是趋势， 但编写小工具应该有更灵活的选择。

**Comment by cdhigh** [comment]
在v1.7里面，如果仅要求产生Python3代码，则修改使用super()调用方式，否则还是使用之前能兼容Python2/3的代码
