### ISSUE TITLE
提示Run-time error '-2147024882 (8007000e)': 对象库未注册

### ISSUE THREAD

**Issue by Cooooldwind** [cdhigh/Vb6Tkinter#19]
关闭提示后就一直打不开了

**Comment by cdhigh** [comment]
另外找一个VB6版本，重新安装，然后单独注册插件即可

**Comment by Cooooldwind** [comment]
> 另外找一个VB6版本，重新安装，然后单独注册插件即可

推荐什么版本呢qwq

**Comment by cdhigh** [comment]
或者安装我正在使用的版本
https://pan.baidu.com/s/1xwMNvUsaeWOexjdo-J3VAA?pwd=7db6
